### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by wojdyr** [LLNL/shroud#304]
Thanks for developing shroud.
Would you mind tagging a new release and uploading it to PyPI?
There are many improvements since v0.12.2 (and `pip install llnl-shroud` installs 0.12.1).

**Comment by ltaylor16** [comment]
I agree it is certainly time for a new release.  I have 'one more feature' to add, then I'll work on doing a release next week.

**Comment by wojdyr** [comment]
Thanks for the release.
Any chance for having v0.13.0 in https://pypi.org/project/llnl-shroud ? It'd make installing it easier for users.

**Comment by wojdyr** [comment]
@ltaylor16 could you update https://pypi.org/project/llnl-shroud/
so that `pip install llnl-shroud` installs the latest versions? Thanks!

**Comment by ltaylor16** [comment]
I added 0.13 to pypi. Thanks for reminding me.
